# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openAndclose.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 631)
        MainWindow.setStyleSheet("QPushButton#pushButton_3,#pushButton_4 {\n"
"background: #000C17;\n"
#"box-shadow: inset 0 2px 8px 0 rgba(0,0,0,0.45);\n"
"opacity: 0.65;\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: #FFFFFF;\n"
"line-height: 22px;\n"
"}\n"
"QPushButton#pushButton_2{\n"
"background: #1890FF;\n"
#"box-shadow: inset 0 2px 8px 0 rgba(0,0,0,0.45);\n"
"opacity: 0.65;\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: #FFFFFF;\n"
"line-height: 22px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(180, -40, 851, 681))
        self.tabWidget.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0);\n"
"text-align: right;\n"
"line-height: 22px;\n"
"}\n"
"QCheckBox{\n"
"    font-family: PingFangSC-Regular;\n"
"    font-size: 14px;\n"
"    color: rgba(0,0,0,0.65);\n"
#"    letter-spacing: 0;\n"
"    text-align: left;\n"
"    line-height: 22px;\n"
"}\n"
"QCheckBox::indicator{\n"
"    background: #FFFFFF;\n"
"    border: 1px solid #40A9FF;\n"
"    border-radius: 2px;\n"
"    border-radius: 2px;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    image: url(./src/qss/复选-已选.svg);\n"
"}\n"
"QRadioButton {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.65);\n"
"text-align: left;\n"
"line-height: 22px;}\n"
"QPushButton#pushButton_13,#pushButton_7,#pushButton_9{\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: #FFFFFF;\n"
"line-height: 22px;\n"
"background: #1890FF;\n"
"border-radius: 4px;\n"
"border-radius: 4px;\n"
"}\n"
"QPushButton#pushButton_8,#pushButton_10,#pushButton_14{\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.65);\n"
"line-height: 22px;\n"
"background: #FFFFFF;\n"
"border: 1px solid #D9D9D9;\n"
"border-radius: 4px;\n"
"border-radius: 4px;\n"
"}\n"
"QLineEdit{\n"
"background: #FFFFFF;\n"
"border: 1px solid rgba(0,0,0,0.15);\n"
"border-radius: 4px;\n"
"border-radius: 4px;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(90, 80, 111, 41))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 141, 31))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(100, 190, 91, 41))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(100, 250, 91, 51))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(100, 350, 91, 51))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(210, 90, 131, 21))
        self.radioButton.setStyleSheet("")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(340, 90, 161, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(190, 140, 591, 32))
        self.lineEdit.setStyleSheet("background: #FFFFFF;\n"
"border: 1px solid rgba(0,0,0,0.15);\n"
"border-radius: 4px;\n"
"border-radius: 4px;")
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(210, 200, 81, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(340, 200, 81, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(460, 200, 81, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_4.setGeometry(QtCore.QRect(590, 200, 81, 21))
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 260, 61, 31))
        self.lineEdit_2.setStyleSheet("background: #FFFFFF;\n"
"border: 1px solid rgba(0,0,0,0.15);\n"
"border-radius: 4px;\n"
"border-radius: 4px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(280, 260, 21, 31))
        self.label_7.setStyleSheet("font: 75 12pt \"新宋体\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(460, 250, 121, 51))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_5.setGeometry(QtCore.QRect(610, 260, 51, 31))
        self.radioButton_5.setStyleSheet("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_6.setGeometry(QtCore.QRect(690, 260, 51, 31))
        self.radioButton_6.setObjectName("radioButton_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_7.setGeometry(QtCore.QRect(150, 400, 161, 31))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_15.setGeometry(QtCore.QRect(330, 400, 161, 31))
        self.checkBox_15.setIconSize(QtCore.QSize(14, 14))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_16.setGeometry(QtCore.QRect(490, 400, 251, 31))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_17.setGeometry(QtCore.QRect(150, 440, 161, 31))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_18.setGeometry(QtCore.QRect(330, 440, 161, 31))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_20.setGeometry(QtCore.QRect(150, 480, 181, 31))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_21.setGeometry(QtCore.QRect(490, 440, 161, 31))
        self.checkBox_21.setObjectName("checkBox_21")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(589, 550, 90, 32))
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(469, 550, 90, 32))
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(300, 270, 111, 16))
        self.label_9.setStyleSheet("color: rgb(227, 0, 17);\n"
"font:  9pt \"新宋体\";\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(750, 400, 41, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 480, 211, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(100, 80, 21, 41))
        self.label_12.setStyleSheet("color: rgb(227, 0, 17);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(100, 260, 21, 31))
        self.label_13.setStyleSheet("color: rgb(227, 0, 17);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(24, 30, 91, 21))
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.65);\n"
"line-height: 22px;}")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(100, 30, 21, 21))
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.45);\n"
"line-height: 22px;}")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(115, 30, 91, 21))
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.50);\n"
"line-height: 22px;}")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 310, 61, 31))
        self.lineEdit_7.setStyleSheet("background: #FFFFFF;\n"
"border: 1px solid rgba(0,0,0,0.15);\n"
"border-radius: 4px;\n"
"border-radius: 4px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(100, 300, 91, 51))
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setStyleSheet("")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(280, 310, 21, 31))
        self.label_24.setStyleSheet("font: 75 12pt \"新宋体\";")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(300, 320, 111, 16))
        self.label_25.setStyleSheet("color: rgb(227, 0, 17);\n"
"font:  9pt \"新宋体\";\n"
"\n"
"")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(100, 310, 20, 31))
        self.label_26.setStyleSheet("color: rgb(227, 0, 17);")
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(90, 80, 121, 51))
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setStyleSheet("")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_19.setGeometry(QtCore.QRect(220, 120, 81, 21))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_22.setGeometry(QtCore.QRect(220, 170, 121, 21))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_23.setGeometry(QtCore.QRect(220, 220, 81, 21))
        self.checkBox_23.setObjectName("checkBox_23")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(589, 550, 90, 32))
        self.pushButton_13.setStyleSheet("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setGeometry(QtCore.QRect(469, 550, 90, 32))
        self.pushButton_14.setStyleSheet("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(100, 90, 21, 31))
        self.label_22.setStyleSheet("color: rgb(227, 0, 17);")
        self.label_22.setObjectName("label_22")
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        self.label_47.setGeometry(QtCore.QRect(115, 30, 91, 21))
        self.label_47.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_47.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.50);\n"
"line-height: 22px;}")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_3)
        self.label_48.setGeometry(QtCore.QRect(24, 30, 91, 21))
        self.label_48.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_48.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.65);\n"
"line-height: 22px;}")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_3)
        self.label_49.setGeometry(QtCore.QRect(100, 30, 21, 21))
        self.label_49.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_49.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.45);\n"
"line-height: 22px;}")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(80, 90, 101, 31))
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setStyleSheet("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.radioButton_51 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_51.setGeometry(QtCore.QRect(190, 90, 61, 31))
        self.radioButton_51.setStyleSheet("QAbstractButton\n"
"{\n"
"font: 75 11pt \"新宋体\";\n"
"}")
        self.radioButton_51.setObjectName("radioButton_51")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(80, 150, 101, 51))
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setStyleSheet("")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(70, 220, 121, 51))
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setStyleSheet("")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.radioButton_61 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_61.setGeometry(QtCore.QRect(280, 90, 71, 31))
        self.radioButton_61.setStyleSheet("QAbstractButton\n"
"{\n"
"font: 75 11pt \"新宋体\";\n"
"}")
        self.radioButton_61.setObjectName("radioButton_61")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_7.setGeometry(QtCore.QRect(280, 160, 71, 31))
        self.radioButton_7.setStyleSheet("QAbstractButton\n"
"{\n"
"font: 75 11pt \"新宋体\";\n"
"}")
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_8.setGeometry(QtCore.QRect(190, 160, 61, 31))
        self.radioButton_8.setStyleSheet("QAbstractButton\n"
"{\n"
"font: 75 11pt \"新宋体\";\n"
"}")
        self.radioButton_8.setObjectName("radioButton_8")
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_24.setGeometry(QtCore.QRect(190, 250, 211, 31))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_25.setGeometry(QtCore.QRect(190, 330, 271, 31))
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_26.setGeometry(QtCore.QRect(190, 370, 281, 31))
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_27.setGeometry(QtCore.QRect(460, 250, 161, 31))
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_28.setGeometry(QtCore.QRect(460, 290, 161, 31))
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_29 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_29.setGeometry(QtCore.QRect(190, 290, 161, 31))
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_30.setGeometry(QtCore.QRect(190, 420, 211, 31))
        self.checkBox_30.setObjectName("checkBox_30")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(589, 550, 90, 32))
        self.pushButton_9.setStyleSheet("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(469, 550, 90, 32))
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(340, 159, 261, 31))
        self.label_10.setStyleSheet("color: rgb(227, 0, 17);\n"
"font:  9pt \"新宋体\";\n"
"")
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(480, 370, 41, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(410, 420, 171, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_50 = QtWidgets.QLabel(self.tab_2)
        self.label_50.setGeometry(QtCore.QRect(115, 30, 91, 21))
        self.label_50.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_50.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.50);\n"
"line-height: 22px;}")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_2)
        self.label_51.setGeometry(QtCore.QRect(24, 30, 91, 21))
        self.label_51.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_51.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.65);\n"
"line-height: 22px;}")
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_2)
        self.label_52.setGeometry(QtCore.QRect(100, 30, 21, 21))
        self.label_52.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_52.setStyleSheet("QLabel {\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: rgba(0,0,0,0.45);\n"
"line-height: 22px;}")
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(80, 90, 21, 31))
        self.label_23.setStyleSheet("color: rgb(227, 0, 17);")
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 130, 181, 51))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 230, 181, 51))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 180, 181, 51))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 180, 91))
        self.label.setStyleSheet("font-family: PingFangSC-Medium;\n"
"font-size: 23px;\n"
"color: #FFFFFF;\n"
"text-align: left;\n"
"background: #002140;\n"
#"box-shadow: 2px 0 6px 0 rgba(0,21,41,0.35);"
)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(0, 90, 180, 571))
        self.label_11.setStyleSheet("background: #001529;\n"
"font-family: PingFangSC-Regular;\n"
"font-size: 14px;\n"
"color: #FFFFFF;\n"
"line-height: 22px;")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.label_11.raise_()
        self.pushButton_4.raise_()
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.tabWidget.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "开机模式:"))
        self.label_3.setText(_translate("MainWindow", "广告资源路径:"))
        self.label_4.setText(_translate("MainWindow", "开机按键:"))
        self.label_5.setText(_translate("MainWindow", "待机等待:"))
        self.label_6.setText(_translate("MainWindow", "检测内容:"))
        self.radioButton.setText(_translate("MainWindow", "断电开机（AC）"))
        self.radioButton_2.setText(_translate("MainWindow", "红外待机唤醒（DC）"))
        self.checkBox.setText(_translate("MainWindow", "音量+-"))
        self.checkBox_2.setText(_translate("MainWindow", "频道+-"))
        self.checkBox_3.setText(_translate("MainWindow", "五维键"))
        self.checkBox_4.setText(_translate("MainWindow", "语音键"))
        self.label_7.setText(_translate("MainWindow", "S"))
        self.label_8.setText(_translate("MainWindow", "远场唤醒:"))
        self.radioButton_5.setText(_translate("MainWindow", "是"))
        self.radioButton_6.setText(_translate("MainWindow", "否"))
        self.checkBox_7.setText(_translate("MainWindow", "网络是否回连成功"))
        self.checkBox_15.setText(_translate("MainWindow", "近场唤醒是否成功"))
        self.checkBox_16.setText(_translate("MainWindow", "移动存储设备挂载是否成功,U盘个数："))
        self.checkBox_17.setText(_translate("MainWindow", "遥控器是否回连成功"))
        self.checkBox_18.setText(_translate("MainWindow", "远场唤醒是否成功"))
        self.checkBox_20.setText(_translate("MainWindow", "蓝牙音箱是否回连成功"))
        self.checkBox_21.setText(_translate("MainWindow", "HDMI出图是否成功"))
        self.pushButton_7.setText(_translate("MainWindow", "创建场景"))
        self.pushButton_8.setText(_translate("MainWindow", "一键调试"))
        self.label_9.setText(_translate("MainWindow", "！输入大于0的整数"))
        self.label_12.setText(_translate("MainWindow", "*"))
        self.label_13.setText(_translate("MainWindow", "*"))
        self.label_14.setText(_translate("MainWindow", "开关机压测"))
        self.label_15.setText(_translate("MainWindow", " / "))
        self.label_20.setText(_translate("MainWindow", "开机流程检测"))
        self.label_21.setText(_translate("MainWindow", "开机等待:"))
        self.label_24.setText(_translate("MainWindow", "S"))
        self.label_25.setText(_translate("MainWindow", "！输入大于0的整数"))
        self.label_26.setText(_translate("MainWindow", "*"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_16.setText(_translate("MainWindow", "直达应用："))
        self.checkBox_19.setText(_translate("MainWindow", "内置应用"))
        self.checkBox_22.setText(_translate("MainWindow", "第三方应用"))
        self.checkBox_23.setText(_translate("MainWindow", "信源"))
        self.pushButton_13.setText(_translate("MainWindow", "创建场景"))
        self.pushButton_14.setText(_translate("MainWindow", "一键调试"))
        self.label_22.setText(_translate("MainWindow", "*"))
        self.label_47.setText(_translate("MainWindow", "恢复出厂设置"))
        self.label_48.setText(_translate("MainWindow", "开关机压测"))
        self.label_49.setText(_translate("MainWindow", " / "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.label_17.setText(_translate("MainWindow", "保留应用："))
        self.radioButton_51.setText(_translate("MainWindow", "是"))
        self.label_18.setText(_translate("MainWindow", "打开串口："))
        self.label_19.setText(_translate("MainWindow", "检测内容："))
        self.radioButton_61.setText(_translate("MainWindow", "否"))
        self.radioButton_7.setText(_translate("MainWindow", "否"))
        self.radioButton_8.setText(_translate("MainWindow", "是"))
        self.checkBox_24.setText(_translate("MainWindow", "检测第三方应用是否存在"))
        self.checkBox_25.setText(_translate("MainWindow", "摄像头驱动是否正常，是否能升降"))
        self.checkBox_26.setText(_translate("MainWindow", "移动存储设备是否能够成功挂载,U盘个数："))
        self.checkBox_27.setText(_translate("MainWindow", "launcher进入正常"))
        self.checkBox_28.setText(_translate("MainWindow", "WiFi驱动是否正常"))
        self.checkBox_29.setText(_translate("MainWindow", "远场语音是否能唤醒"))
        self.checkBox_30.setText(_translate("MainWindow", "批量安装APK（APK路径：xxx）"))
        self.pushButton_9.setText(_translate("MainWindow", "创建场景"))
        self.pushButton_10.setText(_translate("MainWindow", "一键调试"))
        self.label_10.setText(_translate("MainWindow", "严重建议：测试系统版本重置后串口默认打开!"))
        self.label_50.setText(_translate("MainWindow", "开机直达轮询"))
        self.label_51.setText(_translate("MainWindow", "开关机压测"))
        self.label_52.setText(_translate("MainWindow", " / "))
        self.label_23.setText(_translate("MainWindow", "*"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.pushButton_2.setText(_translate("MainWindow", "   开关机流程检测"))
        self.pushButton_3.setText(_translate("MainWindow", "开机直达轮询"))
        self.pushButton_4.setText(_translate("MainWindow", "恢复出厂设置"))
        self.label.setText(_translate("MainWindow", "自动化测试"))
        self.label_11.setText(_translate("MainWindow", "\n"
"      开关机压测"))
